# 04 · Arrays com NumPy
**GA033 · Módulo de introdução à programação científica**

Um vetor de posições, uma tabela de medições e uma matriz de um sistema linear podem ser representados por arrays. Vamos identificar suas dimensões e operar com eles sem perder o significado dos dados.

**Pré-requisitos:** variáveis, listas, funções e laços simples em Python. Execute as células na ordem. Os três exercícios têm soluções recolhidas; nenhuma célula posterior depende de suas respostas.


## O que vamos construir

1. Arrays com dimensões e tipos conhecidos.
2. Seleções, operações e médias de uma tabela pequena.
3. Cópias seguras e dados aleatórios reproduzíveis.
4. A solução de um sistema linear, acompanhada de uma verificação.

Ao terminar, procure explicar tanto o valor de uma resposta quanto seu **shape**.


In [1]:
import numpy as np

print("NumPy:", np.__version__)

NumPy: 2.5.3


## 1. De uma lista a um array

Um **ndarray** guarda dados de um mesmo tipo e organiza esses dados em eixos. Um vetor possui um eixo; uma matriz possui dois. Aqui, cada posição é um número real.


In [2]:
posicoes = np.array([0.0, 0.25, 0.50, 0.75, 1.0])

print("Valores:", posicoes)
print("shape:", posicoes.shape)
print("Número de eixos:", posicoes.ndim)
print("Número de valores:", posicoes.size)
print("dtype:", posicoes.dtype)

Valores: [0.   0.25 0.5  0.75 1.  ]
shape: (5,)
Número de eixos: 1
Número de valores: 5
dtype: float64


**shape** é uma tupla com o comprimento de cada eixo. O vetor acima tem shape **(5,)**; uma matriz com uma linha teria shape **(1, 5)**. São dimensões diferentes, embora ambos contenham cinco números.

O **dtype** descreve o tipo dos valores. Use ponto flutuante quando precisar representar frações: atribuir uma fração a um array de inteiros pode truncá-la.


In [3]:
inteiros = np.array([1, 2, 3], dtype=int)
reais = inteiros.astype(float)
reais[0] = 1.5

linha = posicoes.reshape(1, 5)
print("Inteiros:", inteiros, inteiros.dtype)
print("Reais:", reais, reais.dtype)
print("Vetor:", posicoes.shape, "| matriz com uma linha:", linha.shape)

Inteiros: [1 2 3] int64
Reais: [1.5 2.  3. ] float64
Vetor: (5,) | matriz com uma linha: (1, 5)


Para criar sequências, **linspace** recebe os extremos e o número de pontos; **arange** recebe início, fim excluído e passo. Para dividir um intervalo real em um número conhecido de pontos, linspace deixa essa intenção mais clara.


In [4]:
pontos = np.linspace(0.0, 1.0, 5)
indices = np.arange(5)
zeros = np.zeros(3)

print("Pontos:", pontos)
print("Índices:", indices)
print("Zeros:", zeros)

Pontos: [0.   0.25 0.5  0.75 1.  ]
Índices: [0 1 2 3 4]
Zeros: [0. 0. 0.]


## 2. Índices, fatias e máscaras

Os índices começam em zero. Uma fatia **inicio:fim** inclui o início e exclui o fim. Uma máscara é um array booleano: seleciona as posições onde a condição é verdadeira.


In [5]:
print("Primeiro ponto:", pontos[0])
print("Último ponto:", pontos[-1])
print("Índices 1, 2 e 3:", pontos[1:4])

mascara = pontos >= 0.5
print("Máscara:", mascara)
print("Pontos selecionados:", pontos[mascara])

Primeiro ponto: 0.0
Último ponto: 1.0
Índices 1, 2 e 3: [0.25 0.5  0.75]
Máscara: [False False  True  True  True]
Pontos selecionados: [0.5  0.75 1.  ]


Vamos organizar temperaturas em graus Celsius em uma matriz. **Cada linha é um dia; cada coluna é um sensor.** Essa convenção será importante para as médias.

Em dois eixos, escrevemos **matriz[linha, coluna]**. O símbolo **:** seleciona todas as posições de um eixo.


In [6]:
temperaturas = np.array(
    [
        [18.0, 19.0, 20.0],
        [20.0, 22.0, 24.0],
        [19.0, 21.0, 23.0],
    ]
)

print("shape:", temperaturas.shape)
print("Segundo dia:", temperaturas[1, :])
print("Terceiro sensor:", temperaturas[:, 2])
print("Dia 2, sensor 3:", temperaturas[1, 2])

shape: (3, 3)
Segundo dia: [20. 22. 24.]
Terceiro sensor: [20. 24. 23.]
Dia 2, sensor 3: 24.0


## 3. Operações elemento a elemento e produto matricial

Em arrays, **+**, **-**, **\*** e **\*\*** operam elemento a elemento, se as dimensões forem compatíveis. O símbolo **@** representa o produto matricial.

Uma conversão de temperaturas usa uma operação elemento a elemento. A aplicação de uma matriz a um vetor combina valores por meio de somas de produtos.


In [7]:
kelvin = temperaturas + 273.15
quadrados = pontos**2

A = np.array([[2.0, 1.0], [0.0, 3.0]])
v = np.array([4.0, 5.0])

print("Primeiro dia em kelvin:", kelvin[0])
print("Quadrados:", quadrados)
print("v * v:", v * v)
print("A @ v:", A @ v)
print("v @ v, produto interno:", v @ v)

Primeiro dia em kelvin: [291.15 292.15 293.15]
Quadrados: [0.     0.0625 0.25   0.5625 1.    ]
v * v: [16. 25.]
A @ v: [13. 15.]
v @ v, produto interno: 41.0


Se os dois operandos são matrizes com o mesmo shape, **A \* B** e **A @ B** podem ser permitidos, mas calculam objetos diferentes. Antes de operar, identifique a fórmula matemática desejada.


In [8]:
B = np.array([[1.0, 2.0], [3.0, 4.0]])

print("Produto elemento a elemento:\n", A * B)
print("Produto matricial:\n", A @ B)

Produto elemento a elemento:
 [[ 2.  2.]
 [ 0. 12.]]
Produto matricial:
 [[ 5.  8.]
 [ 9. 12.]]


## 4. O que significa axis?

Uma redução percorre o eixo indicado e o elimina do resultado.

- **axis=0** percorre as linhas: retorna uma média por **sensor**.
- **axis=1** percorre as colunas: retorna uma média por **dia**.
- Sem axis, a média usa todos os valores.

A interpretação depende da organização da tabela.


In [9]:
media_por_sensor = temperaturas.mean(axis=0)
media_por_dia = temperaturas.mean(axis=1)

print("Média por sensor:", media_por_sensor)
print("Média por dia:", media_por_dia)
print("Média de toda a tabela:", temperaturas.mean())

Média por sensor: [19.         20.66666667 22.33333333]
Média por dia: [19. 22. 21.]
Média de toda a tabela: 20.666666666666668


### Exercício 1 · Ler uma tabela

As linhas abaixo são instantes e as colunas são sensores. Calcule a média de cada sensor e selecione os instantes em que o **segundo sensor** mediu pelo menos 21.

Substitua os valores **None** por seus cálculos. A célula já pode ser executada antes de ser preenchida.


In [10]:
dados_ex1 = np.array([[18.0, 20.0], [19.0, 22.0], [20.0, 21.0]])
instantes_ex1 = np.array([0.0, 1.0, 2.0])

medias_ex1 = None  # Calcule uma média por coluna.
selecionados_ex1 = None  # Use a condição sobre dados_ex1[:, 1].

print("Médias:", medias_ex1)
print("Instantes selecionados:", selecionados_ex1)

Médias: None
Instantes selecionados: None


<details>
<summary>Conferir uma solução do exercício 1</summary>

~~~python
import numpy as np

dados = np.array([[18.0, 20.0], [19.0, 22.0], [20.0, 21.0]])
instantes = np.array([0.0, 1.0, 2.0])
medias = dados.mean(axis=0)
selecionados = instantes[dados[:, 1] >= 21.0]
print(medias)        # [19. 21.]
print(selecionados)  # [1. 2.]
~~~

A média com axis=0 retorna duas entradas porque existem dois sensores.

</details>


## 5. Broadcasting: repetir uma operação sem repetir os dados

Queremos retirar, de cada sensor, a sua média. A tabela tem shape **(3, 3)** e o vetor de médias tem shape **(3,)**. O NumPy alinha as dimensões a partir da direita e aplica esse vetor a cada linha.

Dimensões correspondentes são compatíveis quando são iguais ou quando uma delas vale 1. Desenhar os shapes ajuda a evitar operações que são aceitas, mas não representam o cálculo desejado.

A verificação **np.testing.assert_allclose** fica silenciosa quando os valores respeitam as tolerâncias e gera um erro se a comparação falhar.


In [11]:
desvios = temperaturas - media_por_sensor

print("Shapes:", temperaturas.shape, media_por_sensor.shape, "->", desvios.shape)
print("Desvios:\n", desvios)
print("Média dos desvios por sensor:", desvios.mean(axis=0))
np.testing.assert_allclose(desvios.mean(axis=0), 0.0, atol=1e-12)

Shapes: (3, 3) (3,) -> (3, 3)
Desvios:
 [[-1.         -1.66666667 -2.33333333]
 [ 1.          1.33333333  1.66666667]
 [ 0.          0.33333333  0.66666667]]
Média dos desvios por sensor: [ 0.00000000e+00 -1.18423789e-15  1.18423789e-15]


## 6. Nomes, views e cópias

Dar um segundo nome a um array não copia seus dados. Uma **fatia simples** normalmente é uma **view**: acessa parte dos mesmos dados.

**Alterar um elemento** e **reatribuir um nome** são ações diferentes. Alterar a view muda o original; reatribuir o nome da view a um novo array não altera o original.


In [12]:
original = np.array([10.0, 20.0, 30.0, 40.0])
outro_nome = original
trecho = original[1:3]

trecho[0] = 99.0
print("Original após alterar a view:", original)
print("Mesmo objeto?", outro_nome is original)
print("Compartilham dados?", np.shares_memory(original, trecho))

trecho = np.array([-1.0, -2.0])
print("Original após reatribuir o nome trecho:", original)

Original após alterar a view: [10. 99. 30. 40.]
Mesmo objeto? True
Compartilham dados? True
Original após reatribuir o nome trecho: [10. 99. 30. 40.]


Use **copy()** para modificar uma fatia sem alterar a origem. Seleções com máscara ou índices inteiros avançados retornam cópias; não trate toda seleção como uma view.

Aqui usamos arrays numéricos. Cópias de arrays com objetos Python exigem cuidados adicionais com os objetos referenciados.


In [13]:
base = np.array([10.0, 20.0, 30.0, 40.0])
copia = base[1:3].copy()
copia[0] = -100.0

print("Base:", base)
print("Cópia modificada:", copia)
print("Compartilham dados?", np.shares_memory(base, copia))

Base: [10. 20. 30. 40.]
Cópia modificada: [-100.   30.]
Compartilham dados? False


### Exercício 2 · Preservar os dados originais

Copie as duas primeiras linhas de **medidas_ex2** e subtraia, de cada coluna da cópia, a média dessa coluna. Confira que a tabela original ficou intacta e que as médias da cópia modificada são aproximadamente zero.


In [14]:
medidas_ex2 = np.array([[2.0, 8.0], [4.0, 10.0], [6.0, 12.0]])
antes_ex2 = medidas_ex2.copy()

centralizadas_ex2 = None  # Copie a fatia e retire suas médias por coluna.
print("Resposta:", centralizadas_ex2)
print("Original preservado?", np.array_equal(medidas_ex2, antes_ex2))

Resposta: None
Original preservado? True


<details>
<summary>Conferir uma solução do exercício 2</summary>

~~~python
import numpy as np

medidas = np.array([[2.0, 8.0], [4.0, 10.0], [6.0, 12.0]])
antes = medidas.copy()
centralizadas = medidas[:2].copy()
centralizadas -= centralizadas.mean(axis=0)

np.testing.assert_array_equal(medidas, antes)
np.testing.assert_allclose(centralizadas.mean(axis=0), 0.0, atol=1e-12)
print(centralizadas)  # [[-1., -1.], [1., 1.]]
~~~

copy() é essencial porque a atualização com -= modifica os dados.

</details>


## 7. Aleatoriedade reproduzível e vetorização

Um gerador com semente explícita permite repetir o exemplo no mesmo ambiente. Seu estado avança a cada sorteio; execute novamente a célula inteira para reiniciar a sequência.

Vamos calcular os mesmos quadrados com um laço Python e com uma operação do NumPy.


In [15]:
rng = np.random.default_rng(2026)
amostra = rng.normal(loc=0.0, scale=1.0, size=6)

por_laco = np.empty_like(amostra)
for i in range(amostra.size):
    por_laco[i] = amostra[i] ** 2

por_numpy = amostra**2
print("Amostra:", np.round(amostra, 3))
print("Resultados equivalentes?", np.allclose(por_laco, por_numpy))

Amostra: [-0.793  0.241 -1.896  1.396  0.638 -0.292]
Resultados equivalentes? True


As duas versões visitam os $n$ valores: ambas têm custo $\Theta(n)$ neste cálculo. A operação vetorizada costuma ser mais rápida porque o trabalho repetitivo acontece em rotinas compiladas, com menor sobrecarga por elemento.

Isso não significa que os laços deixaram de existir nem que a complexidade mudou. Ganhos de tempo dependem dos dados e do ambiente; não precisamos de um benchmark longo para compreender essa distinção.


## 8. Resolver um sistema e conferir a resposta

Para $Au=b$, use **np.linalg.solve(A, b)**. Calcular explicitamente a inversa não é necessário para encontrar $u$.

No sistema abaixo, podemos verificar à mão que $u=(1,2)^T$. O **resíduo** $r=Au-b$ mede quanto a resposta calculada deixa de satisfazer as equações.


In [16]:
A_sistema = np.array([[3.0, -1.0], [-1.0, 2.0]])
b_sistema = np.array([1.0, 3.0])

u_sistema = np.linalg.solve(A_sistema, b_sistema)
residuo = A_sistema @ u_sistema - b_sistema

print("Solução:", u_sistema)
print("Resíduo:", residuo)
print("Norma do resíduo:", np.linalg.norm(residuo))
np.testing.assert_allclose(u_sistema, [1.0, 2.0], atol=1e-12)

Solução: [1. 2.]
Resíduo: [0. 0.]
Norma do resíduo: 0.0


### Exercício 3 · Resolver e verificar

Resolva
\[
\begin{bmatrix}2&1\\1&3\end{bmatrix}
\begin{bmatrix}u_0\\u_1\end{bmatrix}
=
\begin{bmatrix}4\\7\end{bmatrix}.
\]

Calcule o resíduo e sua norma. Não use a inversa da matriz.


In [17]:
A_ex3 = np.array([[2.0, 1.0], [1.0, 3.0]])
b_ex3 = np.array([4.0, 7.0])

u_ex3 = None  # Resolva com np.linalg.solve.
if u_ex3 is None:
    print("Preencha u_ex3 para calcular o resíduo.")
else:
    residuo_ex3 = A_ex3 @ u_ex3 - b_ex3
    print("Solução:", u_ex3)
    print("Norma do resíduo:", np.linalg.norm(residuo_ex3))

Preencha u_ex3 para calcular o resíduo.


<details>
<summary>Conferir uma solução do exercício 3</summary>

~~~python
import numpy as np

A = np.array([[2.0, 1.0], [1.0, 3.0]])
b = np.array([4.0, 7.0])
u = np.linalg.solve(A, b)
r = A @ u - b

np.testing.assert_allclose(u, [1.0, 2.0], atol=1e-12)
print(u)
print(np.linalg.norm(r))
~~~

Um resíduo pequeno é uma verificação útil. Em sistemas mal condicionados, ele sozinho não garante erro pequeno na solução. Aqui também conhecemos a resposta exata.

</details>


## Para continuar

Confira o significado dos eixos, os shapes e o tipo numérico. Distinga operações elemento a elemento de produtos matriciais; ao modificar uma seleção, verifique se ela compartilha dados com a origem.

**Fontes consultadas:** ideias de organização do [curso NumPy/SciPy de Diego Volpatto](https://github.com/volpatto/numpy_scipy_course), com exemplos e redação novos para este módulo; documentação oficial de [arrays](https://numpy.org/doc/stable/user/absolute_beginners.html), [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html), [cópias e views](https://numpy.org/doc/stable/user/basics.copies.html), [geradores aleatórios](https://numpy.org/doc/stable/reference/random/generator.html) e [solve](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html).

**Autor:** Diego Tavares Volpatto. **Licença:** [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).


[← Caderno anterior](03-funcoes.ipynb) · [Índice do curso](../README.md) · [Próximo caderno →](05-graficos-e-resultados.ipynb)

Autor: Diego Tavares Volpatto · [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.pt-br)